### PR TITLE
Provide default JS and Sass

### PR DESCRIPTION
**Pull request by glebm**
Set up the engine to provide default JS and CSS.
For now, only added support for select2 and time ago.
On the CSS side, there is only a default bootstrap-sass theme for now.

This is integrated with the dummy app (`rake dev`).

Perhaps Bootstrap styles can live in a separate gems in the future, but I've just put it here for now.

### Messageboard:

thredded1

### Topic show:

thredded2

### New private topic:

thredded3

### CODE REVIEW

**Comment by jayroh** [comment]
This is currently in progress within a handful of simultaneous branches making their way into v0.1.0. The first effort was allowing everything to be packaged up in theme directories :white_check_mark:. The second effort is currently ongoing and is a bourbon/neat theme after re-doing all view layer markup in a "default" theme :clock2:. Following up after that would be to simulate the style work from the first them, with bootstrap (and then maybe foundation).

I'll close this out as a result and we'll continue on with the roadmap. Thank you @glebm for all this hard work. I really appreciate it.

**Comment by glebm** [comment]
Cool, I hope I have time to work on this some day :+1:

**Comment by jayroh** [comment]
You're, like ... busy in London being brilliant and smart n shit. No?

You get a pass for however long :)

**Comment by glebm** [comment]
Still learning the ropes, getting up to speed at Google is a lengthy process. Enjoying it though :)

**Pull request closed without merging**
